info.id = "151"
info.name = "Vmware 16"
info.icon = "vmware.png"
info.desc = "史上最伟大网管精简的vmware虚拟机"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vmware"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FZWQtVW95WDlUeEl0bDJTalVQajVjWUJSUmZyeWlQZmNlYlU4NklYQ2g3dndRP2U9MW94TFZl..exe"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "vmware.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"