-- This source code was auto-generated by updater.bat

AppStore = {}
AppStore.path = '.'
AppStore.config = {}

CatalogInfo = {}
AppInfo = {}

local catalog = nil 
local info = {}

CatalogInfo['00-系统维护'] = {}
catalog = CatalogInfo['00-系统维护']
catalog.name = '00-系统维护'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "360sd"
info.name = "360杀毒"
info.icon = "360sd.png"
info.desc = "360杀毒极速版"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "360sd"
info.download_page = "https://sd.360.cn/download_center.html"
info.direct_url = [[https://[^\"]*/360sd/[^\"]*x64_plus[^\"]*]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\360安全中心\\360杀毒\\打开360杀毒.lnk"
info.app_setup_args = "/S"
info.app_setup = "360sdsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "360wifi"
info.name = "360免费WIFI"
info.icon = "360wifi.png"
--info.icon = app.call('varstr', [[%SystemDrive%\windows\system32\ico\wifi.ico]])
info.desc = "可以和其它电脑、手机等无线设备建立连接、共享网络"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://pan.bilnn.cn/api/v3/file/sourcejump/lmlKXBIb/imTYH3iSrD6IxFUrVMHlHfVQF_t09eytRLN5fRwr7m4*]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "360wifi"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "360免费WIFI.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "balenaEtcher"
info.name = "balenaEtcher写盘"
info.icon = "balenaEtcher.png"
info.desc = "balenaEtcher镜像写入工具,可以写入img、dmg等磁盘镜像"
info.star = "商店应用"
info.download_page = "https://github.com/balena-io/etcher/releases/tag/v1.7.8"
info.direct_url = [[https://github.91chi.fun/https://github.com/balena-io/etcher/releases/download/v1.7.8/balenaEtcher-Portable-1.7.8.exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "windowsup"
info.app_runpath = "temp"
info.app_setup_args = "/s"
info.app_setup = "balenaEtcher.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "cleanmaster"
info.name = "系统清理"
info.icon = "cleanmaster.png"
info.desc = "清理谷歌浏览器、其它软件的缓存和上网痕迹"
info.star = "内置应用"
info.appmode = "runapp"
info.adminmode = "1"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[wxsui\ui_appstore\soft\cleanmaster.exe]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "GRUNFM_S"
info.name = "GrubFM启动(签名)"
info.icon = "cong.png"
info.desc = "Grubfm启动盘制作器，此版本可导入证书以支持安全启动"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FYnBWckpucUpEMU5yRWVHenZla1JSRUIyQWZJMVpiSnh4dUJtVkk3ZEprVmJRP2U9Zm5xbms1.exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "nbpe"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[grubfm_S.exe]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "iemode"
info.name = "企业网站列表管理器"
info.icon = "cong.png"
info.desc = "企业网站列表管理器,制作Edge浏览器导入的xml文件,需要在edge并输入edge://compat/sitelistmanager导入或看关于中的说明"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FZTJzalhHMDBVTkVtNDMtRk43ai0yQUJweWRmMmU3MEFDOHZWa0ItX01rSU9BP2U9ZTM1ZXA3.exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "iemode"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[EMIESiteListManager.exe]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "NBServerPE"
info.name = "NBServerPE_1026"
info.icon = "cong.png"
info.desc = "NewBeePEServer版!,一款Windows高质量PE，会叫!WIFI\\ISCSI\\网启服务\\浏览器\\VM\\开.Net的NewBeePE"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FV0RBWWlSMlVfTkZqbXRLQVNLNnpsd0JxMmJWWV9iUGVVZUt4ZVB6bzh5OC13P2U9bEl3QXNp.wim]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "nbpe"
info.winpe = "1"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[NewBeePlus_server.wim]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "nbtool_bootfire"
info.name = "UEFI序列_BCD编辑"
info.icon = "nbtool_bootfire.png"
info.desc = "调整UEFI序列，选中序列中网启PXE项或BCD菜单项可立即启动(一次性启动)"
info.star = "内置应用"
info.appmode = "runapp"
info.adminmode = "1"
info.nbapp = "bootfire"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[winxshell -ui -jcfg wxsui\ui_appstore\nbtool_bootfire.jcfg]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "nbtool_ck"
info.name = "修复分区错误"
info.icon = "nbtool_ck.png"
info.desc = "修复分区错误Chkdsk"
info.star = "内置应用"
info.appmode = "runapp"
info.adminmode = "1"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[winxshell -ui -jcfg wxsui\ui_appstore\nbtool_ck.jcfg]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "nbtool_NVME"
info.name = "NVME启动支持"
info.icon = "nbtool_ck.png"
info.desc = "使目标分区的系统支持NVME启动"
info.star = "内置应用"
info.appmode = "runapp"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[winxshell -script wxsui\ui_appstore\nbtool_NVME.lua]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "nbtool_Panfu"
info.name = "系统盘符重置"
info.icon = "nbtool_ck.png"
info.desc = "使目标分区的系统盘符重置，即删除注册表项MountedDevices下的所有值"
info.star = "内置应用"
info.appmode = "runapp"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[winxshell -script wxsui\ui_appstore\nbtool_Panfu.lua]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "petools"
info.name = "导出petools示例"
info.icon = "cong.png"
info.desc = "导出petools示例到根目录，方便PE开机后自动固定ip，自动架设网启服务器，自动还原系统镜像，自动叫……"
info.star = "内置应用"
info.appmode = "runapp"
info.nbapp = "petools"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[winxshell -script wxsui\ui_appstore\nbtool_petools.lua]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "NewBeePE"
info.name = "NewBeePE_0501"
info.icon = "cong.png"
info.desc = "NewBeePE,一款Windows高质量PE，会叫?WIFI\\ISCSI\\网启服务\\浏览器\\VM\\开.Net的NewBeePE"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FYjZDRGJBT3lJaE9rc2VKMlpqN2U4b0JsS0EyMmY1cU5pSzZtM3B1aVNLTXB3P2U9ZXZBVnZE.wim]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "nbpe"
info.winpe = "1"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[NewBeePlus.wim]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "Printer_tools"
info.name = "打印机工具_添加LPD"
info.icon = "printer.png"
info.desc = "打印机专用维护工具，添加LPD打印机，打开Windows7/10的LPD服务器功能，并添加LPD打印机"
info.star = "内置应用"
info.appmode = "runapp"
info.adminmode = "1"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[wxsui\ui_appstore\soft\batch_tool\Printer_tools.bat]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "timesync"
info.name = "时间同步"
info.icon = "timesync.png"
info.desc = "校准电脑时间"
info.star = "内置应用"
info.appmode = "runapp"
info.adminmode = "1"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[wxsui\ui_appstore\timesync.exe /auto]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "wimboot"
info.name = "添加PE[WIM/VHD]"
info.icon = "nt6.png"
info.desc = "你可以一键重启到PE，或添加Wim、vhd镜像到开机菜单"
info.star = "内置应用"
info.appmode = "wimboot"
info.nbapp = "wimboot"

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "WUBlocker"
info.name = "WUBlocker禁止更新"
info.icon = "WUBlocker.png"
info.desc = "震精网吧界的老牌远程工具，作者一直保证性欲"
info.star = "商店应用"
info.download_page = [[https://www.sordum.org/9470/windows-update-blocker-v1-7/]]
--info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FYkt0Ylh3cVZ2UkJuNmJEaW9QZTZHb0JqeVJWWGpOa1pBcEpHVkZTcWl4WWdBP2U9MHNrSDlk.zip]]
info.direct_url = [[https://www.sordum.org/files/downloads.php?st-windows-update-blocker]]
info.nbapp = "WUBlocker"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "WUBlocker.zip"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['11-聊天冲浪'] = {}
catalog = CatalogInfo['11-聊天冲浪']
catalog.name = '11-聊天冲浪'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "360ChromeX"
info.name = "360极速浏览器X"
info.star = "商店应用"
info.desc = "360"
info.icon = "360ChromeX.ico"
info.download_page = "https://dl.qq.com/wechat"
info.direct_url = "https://down.360safe.com/cse/360csex_setup.exe"
info.appmode = "StoreApp_direct_url"
info.nbapp = "360ChromeX"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\360安全中心\\360 极速浏览器X\\360 极速浏览器X.lnk"
info.app_setup_args = "--silent-install=3_1_1"
info.app_setup = "360极速浏览器X.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "centbrowser"
info.name = "百分浏览器"
info.icon = "centbrowser.png"
info.desc = "追求速度、简约和安全的网络浏览器"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "centbrowser"
info.download_page = "https://www.centbrowser.cn/"
info.direct_url = [[https://[^\"]*/win_stable/[^\"]*/[^\"]*x64.exe]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Cent Browser.lnk"
info.app_setup_args = "--cb-auto-update"
info.app_setup = "百分浏览器.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "chrome"
info.name = "谷歌浏览器"
info.star = "网盘应用"
info.desc = "谷歌出口"
info.icon = "chrome.ico"
info.download_page = "https://dl.qq.com/wechat"
info.direct_url = "https://pan.bilnn.cn/api/v3/file/sourcejump/1Mxx93iw/2HKHqPKiE24t3NYrMf55VhZt2OZTtGqxZpy5iNitKVU*"
info.appmode = "StoreApp_direct_url"
info.nbapp = "chrome"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Internet Explorer\\Quick Launch\\Google Chrome.lnk"
info.app_setup_args = "/install" --静默参数/silent
info.app_setup = "谷歌浏览器.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "qq"
info.name = "腾讯QQ"
info.icon = "QQ.ico"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "qq"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\腾讯软件\\QQ\\腾讯QQ.lnk"
info.app_setup_args = "/S"
info.app_setup = "腾讯QQ.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "tim"
info.name = "腾讯TIM"
info.icon = "tim.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "tim"
info.download_page = [[https://im.qq.com/rainbow/TIMDownload]]
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*/TIM[^\"]*]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\腾讯软件\\TIM\\TIM.lnk"
info.app_setup_args = "/S"
info.app_setup = "腾讯tim.exe"
info.user_agent = [[--user-agent=" Chrome/110.0.5481.78"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "wechat"
info.name = "微信电脑版"
info.star = "商店应用"
info.desc = "腾讯出品"
info.icon = "WeChat.ico"
info.download_page = "https://dl.qq.com/wechat"
info.direct_url = "https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe"
info.appmode = "StoreApp_direct_url"
info.nbapp = "wechat"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\微信\\微信.LNK"
info.app_setup_args = "/S"
info.app_setup = "微信电脑版.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['12-影音娱乐'] = {}
catalog = CatalogInfo['12-影音娱乐']
catalog.name = '12-影音娱乐'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "121"
info.name = "kodi"
info.icon = "kodi.png"
info.desc = "I'm Kodi，每一天 乐 - 在 - P - O -R -*"
info.star = "商店应用(解析)"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://[^\"]*/releases/windows/win64/kodi[^\"]*]]
info.appmode = "StoreApp_analysis_url"
info.nbapp = "kodi"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Kodi\\Kodi.lnk"
info.app_setup_args = "/S"
info.app_setup = "kodisetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "potplayer"
info.name = "potplayer"
info.icon = "potplayer.png"
info.desc = "I'm Potplayer，每一天 乐 - 在 - * - *"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup.exe"
info.nbapp = "potplayer"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Potplayer\\PotPlayer.lnk"
info.app_setup_args = "/S"
info.app_setup = "potplaysetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "vlc"
info.name = "vlc播放器"
info.icon = "vlc播放器.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "商店应用(解析)"
info.download_page = "https://www.videolan.org/"
info.direct_url = [[get.videolan.org/[^\"]*/win64/[^\"]*win64.exe]]
info.direct_url_prefix = [[https://]]
info.appmode = "StoreApp_analysis_url"
info.nbapp = "vlc"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\VideoLAN\\VLC media player.lnk"
info.app_setup_args = "/S"
info.app_setup = "vlcsetup.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "124"
info.name = "迅雷影音"
info.icon = "xmp.png"
info.desc = "专业播放 尽享精彩 百种格式  超清视频  想看就看"
info.star = "商店应用(解析)"
info.download_page = "https://dl.xunlei.com"
info.direct_url = [[https://[^\"]*/xmp/[^\"]*.exe]]
info.appmode = "StoreApp_analysis_url"
info.nbapp = "xmp"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\迅雷软件\\迅雷影音\\迅雷影音.lnk"
info.app_setup_args = "/S"
info.app_setup = "xmpsetup.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['13-文档办公'] = {}
catalog = CatalogInfo['13-文档办公']
catalog.name = '13-文档办公'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "dinggov"
info.name = "浙政钉"
info.icon = "dinggov.png"
info.desc = "根据2020年浙江省深化“最多跑一次”改革推进政府数字化转型工作要点，为实现基本建成“掌上办公之省”年度工作目标，省大数据局联合阿里巴巴启动了“浙政钉”的迭代升级，请按迁移计划下载并使用浙政钉客户端。"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "dinggov"
info.download_page = "https://www.ding.zj.gov.cn/pc/index.html#/"
info.direct_url = [[https://[^\"]*/pc/[^\"]*]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\浙政钉\\浙政钉.lnk"
info.app_setup_args = "/S"
info.app_setup = "浙政钉.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "dingtalk"
info.name = "钉钉"
info.icon = "dingtalk.png"
info.desc = "让企业进入高效移动办公时代"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/win_downloader/dingtalk_downloader.exe"
info.nbapp = "dingtalk"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "钉钉.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "wps2016"
info.name = "wps2016"
info.icon = "wps.png"
info.desc = "金山出品"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://wdl1.cache.wps.cn/wps/download/W.P.S.7400.12012.0.exe"
info.nbapp = "wps2016"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\WPS Office\\产品更新信息.lnk"
info.app_setup_args = "/S"
info.app_setup = "wps2016.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['14-远程工具'] = {}
catalog = CatalogInfo['14-远程工具']
catalog.name = '14-远程工具'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "Alpemix"
info.name = "Alpemix远程"
info.icon = "Alpemix远程.png"
info.desc = "Alpemix远程是国外的免费远程软件"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://www.alpemix.com/site/Alpemix.exe"
info.nbapp = "Alpemix"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "Alpemix.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "AnyDesk"
info.name = "AnyDesk"
info.icon = "AnyDesk.png"
info.desc = "轻量化设计。流畅的远程桌面连接。轻松的在线远程协作。与早期的Windows版本兼容。更新始终免费。"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://download.anydesk.com/AnyDesk.exe"
info.nbapp = "AnyDesk"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "AnyDesk.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "dbadmin"
info.name = "深蓝远程"
info.icon = "Dbadmin.png"
info.desc = "震精网吧界的老牌远程工具，作者一直保证性欲"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "http://down.slser.com/down.php"
info.nbapp = "dbadmin"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "dbadmin.7z"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "oraylite"
info.name = "向日葵受控端"
info.icon = "向日葵.png"
info.desc = "十几年历史的远程软件"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://sunlogin.oray.com/zh_CN/download/download?id=152&x64=1"
info.nbapp = "oraylite"
info.app_runpath = "temp"
info.app_setup_args = "--mod=green"
info.app_setup = "向日葵lite.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "oraynew"
info.name = "向日葵新版"
info.icon = "向日葵.png"
info.desc = "该版本需要登陆才能使用!"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://sunlogin.oray.com/zh_CN/download/download?id=65&x64=1"
info.nbapp = "oraynew"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "向日葵新版.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "RustDesk"
info.name = "RustDesk"
info.icon = "RustDesk.png"
info.desc = "RustDesk远程"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "RustDesk"
info.download_page = "http://RustDesk.com/zh/"
info.direct_url = [[http:*[^\"]*[^\"]*/download/*[^\"]*x64.zip]]
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "RustDesk.7z"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "todesk"
info.name = "ToDesk"
info.icon = "todesk.png"
info.desc = "新品远程软件ToDesk完整版"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.todesk.com/windows/ToDesk_Setup.exe"
info.nbapp = "todesk"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\ToDesk\\ToDesk.lnk"
info.app_setup_args = "/S"
info.app_setup = "todesksetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "todesklite"
info.name = "ToDeskLite"
info.icon = "todesk.png"
info.desc = "新品远程软件todesk受控端"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.todesk.com/windows/ToDesk_Lite.exe"
info.nbapp = "todesklite"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "todesklite.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['15-虚拟机类'] = {}
catalog = CatalogInfo['15-虚拟机类']
catalog.name = '15-虚拟机类'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "152"
info.name = "VM16完整版"
info.icon = "vmware.png"
info.desc = "官方完整版vmware"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vm16"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.softmgr.qq.com/original/System/VMware-workstation-full-16.1.2-17966106.exe"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "vmsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "vmtool64"
info.name = "VMTool64"
info.icon = "VMTool64.png"
--info.icon = app.call('varstr', [[%SystemDrive%\windows\system32\ico\wifi.ico]])
info.desc = "虚拟机启动时,方便和主机间复制粘贴、拖放文件"
info.star = "网盘应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FVHBiUko1MEdpbEJrcjNnZDdhbF90VUJEUTBYVXRQcmhralE4N2NISUtLWWRnP2U9TzdTb0ZB..exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "vmtool64"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "vmtool64.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 1 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "151"
info.name = "Vmware 16"
info.icon = "vmware.png"
info.desc = "史上最伟大网管精简的vmware虚拟机"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vmware"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FZWQtVW95WDlUeEl0bDJTalVQajVjWUJSUmZyeWlQZmNlYlU4NklYQ2g3dndRP2U9MW94TFZl..exe"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "vmware.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['16-热门游戏'] = {}
catalog = CatalogInfo['16-热门游戏']
catalog.name = '16-热门游戏'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "105"
info.name = "105算牌器"
info.icon = "105.png"
info.desc = "本土化的棋牌游戏大厅"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://www.jovi.cn/jpq/%E7%AB%A5%E5%BF%83%E5%9C%86%E8%AE%B0%E7%89%8C%E5%99%A8-%E5%90%8C%E5%9F%8E%E6%B8%B8105.exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "105"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "105算牌器.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "dx"
info.name = "DX依赖包"
info.icon = app.call('varstr', [[%SystemDrive%\windows\system32\dxdiag.exe,F]])
info.desc = "directx，玩GTA游戏需要"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FUml0QlJ4UkJqSkhoa09jczRiNFFOUUJmZkRldTBpU25SQkZSOVlUb2RYUXFnP2U9VW9zR2hq..exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "dx"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "dx.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "flash"
info.name = "FLASH中心"
info.icon = "flash.png"
info.desc = "流氓软件flash，但能玩游戏模鱼"
info.star = "商店应用"
info.download_page = "https://www.flash.cn"
info.direct_url = [[https://static.ffzww.com/download/flashcenter/FlashCenter_Site_Setup.exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "flash"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "flashsetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "start"
info.name = "START云游戏"
info.icon = "start.png"
info.desc = "START云游戏，多端畅享!电视直接玩游戏，一步到位"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "start"
info.download_page = "https://start.qq.com"
info.direct_url = [[https://[^\"]*/win.client/installer/[^\"]*]]
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\腾讯游戏\\START\\START.lnk"
info.app_setup_args = "/S"
info.app_setup = "startsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "tcy"
info.name = "嵊州同城游"
info.icon = "tcy.png"
info.desc = "本土化的棋牌游戏大厅"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://www.tcy365.com/hall/downloadhall.html?hallid=680]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "tcy"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "tcysetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "vc"
info.name = "VC依赖包"
info.icon = app.call('varstr', [[%SystemDrive%\windows\system32\msiexec.exe,F]])
info.desc = "基础VC支持，安装游戏需要"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FVk5ialY1b1A3UkhvQXRkQ1hMZUplSUJ2eGkwRDFNenRnSGxkT191UlN1UlJBP2U9aUUyNmRq..exe]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "dx"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "vc.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.pemode = "1"
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['18-装机必备'] = {}
catalog = CatalogInfo['18-装机必备']
catalog.name = '18-装机必备'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "7zip"
info.name = "7zip压缩"
info.icon = "7zip.png"
info.desc = "7-Zip 是一款拥有极高压缩比的开源压缩软件。"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "7zip"
info.download_page = "https://www.7-zip.org"
info.direct_url = [[https://www.7-zip.org/a/7z2201-x64.exe]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\7-Zip\\7-Zip File Manager.lnk"
info.app_setup_args = "/S"
info.app_setup = "7z2201-x64.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "DriverAngel"
info.name = "驱动天使"
info.icon = "DriverAngel.png"
info.desc = "一款在线安装驱动的软件"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "DriverAngel"
info.download_page = "http://www.qudongtianshi.com"
info.direct_url = [[http://www.qudongtianshi.com/file/DriverAngel_Setup.exe]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\驱动天使\\驱动天使.lnk"
info.app_setup_args = "/S"
info.app_setup = "驱动天使.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "DriverBooster.png"
info.name = "Driver Booster Pro"
info.icon = "DriverBooster.png"
info.desc = "一款国外在线安装驱动的软件"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "drivermax"
info.download_page = "https://www.iobit.com/en/index.php"
info.direct_url = [[https://cdn.iobit.com/dl/driver_booster_setup.exe]]
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "DriverBoosterSetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "drivermax"
info.name = "DriverMax"
info.icon = "drivermax.png"
info.desc = "一款国外在线安装驱动的软件"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "drivermax"
info.download_page = "https://www.drivermax.com/"
info.direct_url = [[https://www.drivermax.com/soft/dmx/drivermax.exe]]
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "DrivermaxSetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "huorong"
info.name = "火绒安全"
info.icon = "huorong.png"
info.desc = "火绒安全杀毒，适合去广告，正常系统下安装用，PE下没什么用!"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "huorong"
info.download_page = "https://down7.huorong.cn/sysdiag-full-5.0.69.2-2022.7.19.1.exe"
info.direct_url = [[https://down7.huorong.cn/sysdiag-full-5.0.69.2-2022.7.19.1.exe]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\火绒安全实验室\\Sysdiag\\火绒安全软件.lnk"
info.app_setup_args = "/help"
info.app_setup = "火线安全.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "mspcm"
info.name = "微软电脑管家"
info.icon = "mspcm.png"
info.desc = "微软出的电脑管家，拦截弹出广告，设置默认浏览器"
info.star = "商店应用"
info.download_page = "https://pcmanager.microsoft.com/cn"
info.direct_url = "https://aka.ms/PCManager10000"
info.nbapp = "qqwubi"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "微软电脑管家.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "qqpy"
info.name = "QQ拼音输入法"
info.icon = "qqpy.png"
info.desc = "精准输入 畅快表达"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "http://qq.pinyin.cn/download_pc.php?t=py"
info.nbapp = "qqpy"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "QQ拼音输入法.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "qqwubi"
info.name = "QQ五笔输入法"
info.icon = "qqwubi.png"
info.desc = "精准输入 畅快表达"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "http://qq.pinyin.cn/download_pc.php?t=wb"
info.nbapp = "qqwubi"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "QQ五笔输入法.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "sougoupy"
info.name = "搜狗拼音输入法"
info.icon = "sougoupy.png"
info.desc = "比较流行的搜狗拼音输入法"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "sougoupy"
info.download_page = "https://shurufa.sogou.com"
info.direct_url = [[https://[^\"]*/dl/[^\"]*pinyin[^\"]*]]
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\搜狗输入法\\卸载.lnk"
info.app_setup_args = "/S"
info.app_setup = "搜狗拼音输入法.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "winrarx64"
info.name = "WinRAR压缩x64"
info.icon = "winrar压缩.png"
info.desc = "winrar压缩 使用最广泛的压缩软件"
info.star = "商店应用(解析)"
info.download_page = "https://www.win-rar.com/postdownload.html?&L=7"
info.direct_url = [[fileadmin/[^\"]*/winrar/[^\"]*]]
info.direct_url_prefix = [[https://www.win-rar.com/]]
info.appmode = "StoreApp_analysis_url"
info.nbapp = "winrar"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\WinRAR\\WinRAR.lnk"
info.app_setup_args = "/S"
info.app_setup = "WinRAR压缩x64.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "xunlei"
info.name = "迅雷下载"
info.icon = "xunlei.png"
info.desc = "迅雷下载官方版"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "xunlei"
info.download_page = "https://dl.xunlei.com/"
info.direct_url = [[https://[^\"]*/thunder[^\"]*/[^\"]*XunLeiWebSetup[^\"]*]]
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\迅雷软件\\迅雷\\迅雷.lnk"
info.app_setup_args = "/S"
info.app_setup = "迅雷.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "xybtype"
info.name = "逍遥笔输入法"
info.icon = "xybtype.png"
info.desc = "专业手写识别软件"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://sm.myapp.com/original/Input/xyb8.4.0.2.exe"
info.nbapp = "xybtype"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "逍遥笔输入法exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['88-更多商店'] = {}
catalog = CatalogInfo['88-更多商店']
catalog.name = '88-更多商店'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "360softmgr"
info.name = "360软件管家"
info.icon = "360softmgr.png"
info.desc = "360软件管家"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "360softmgr"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly84ODVmeXouc2hhcmVwb2ludC5jb20vOnU6L3MvTkJQRS9FYmhqRFZVRFhEMUpwdUhjS1pNekFxY0JIYVBLcnZyOHdoSDhsaVc4eHd5bVJnP2U9c3owaWxV..exe"
info.app_runpath = [["%temp%\\360SoftMgr\\SoftMgr\\SoftMgr.exe"]]
info.app_setup_args = "/S"
info.app_setup = "360softmgr.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "qqsoftmgr"
info.name = "QQ软件管理"
info.icon = "qqsoftmgr.png"
info.desc = "QQ软件管理"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "qqsoftmgr"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://pan.bilnn.cn/api/v3/file/sourcejump/mYDNglIw/m_kt3ZBGxm-KmdQl82SAwaTmrtVaBQJU3DwVBI8kbKw*"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "qqsoftmgr.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['89-系统镜像'] = {}
catalog = CatalogInfo['89-系统镜像']
catalog.name = '89-系统镜像'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "BaiPiao10"
info.name = "Win10新版"
info.icon = "nt6.png"
info.desc = [[白嫖win10最新 ESD镜像\家庭版\零售版\商业版]]
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.appmode = "StoreApp_BaiPiao"
info.nbapp = "baipiao10"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[win10.esd]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "BaiPiao11"
info.name = "Win11新版"
info.icon = "nt6.png"
info.desc = [[白嫖win11最新 ESD镜像\家庭版\零售版\商业版]]
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink?linkid=2156292"
info.appmode = "StoreApp_BaiPiao"
info.nbapp = "baipiao11"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[win11.esd]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "ProfessionalEducation"
info.name = "Win10专业教育版"
info.icon = "nt6.png"
info.desc = "Win10专业教育版镜像ESD 19044"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[http://dl.delivery.mp.microsoft.com/filestreamingservice/files/e7aa8b81-ee80-4b52-8f04-c364f0ce1af1/19044.1288.211006-0501.21h2_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_zh-cn.esd]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "windows_proedu"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[win10.esd]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "Win11_Business"
info.name = "Win11商业版"
info.icon = "nt6.png"
info.desc = "Win11 Business 版本ESD镜像22000.318"
info.star = "商店应用"
info.download_page = "https://go.microsoft.com/fwlink/?LinkId=841361"
info.direct_url = [[http://dl.delivery.mp.microsoft.com/filestreamingservice/files/73bedbd0-f169-4f2b-82ea-e6fa078838d6/22000.318.211104-1236.co_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_zh-cn.esd]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "windows_proedu"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = [[win11.esd]]
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "windowsup"
info.name = "易升系统安装"
info.icon = "windows.png"
info.desc = "Windows 10 易升属于官方的升级工具"
info.star = "商店应用"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://go.microsoft.com/fwlink/?LinkID=799445]]
info.appmode = "StoreApp_direct_url"
info.nbapp = "windowsup"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "windowsupgrade.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['999-关于'] = {}
catalog = CatalogInfo['999-关于']
catalog.name = '999-关于'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "cmd"
info.name = "CMD命令行"
info.icon = app.call('varstr', [[%SystemDrive%\windows\system32\cmd.exe,F]])
info.desc = "cmd"
info.star = "本地应用"
info.appmode = "runapp"
info.nbapp = "cmd"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[%SystemDrive%\windows\system32\cmd.exe]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "update"
info.name = "更新商店"
info.icon = "update.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "系统应用"
info.appmode = "runapp"
info.nbapp = "update"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[wxsUI\UI_AppStore\appstore.bat]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "buildappstore"
info.name = "生成新商店"
info.icon = "build.png"
info.desc = "生成拥有自煮姿势产权的新商店"
info.star = "系统应用"
info.appmode = "runapp"
info.nbapp = "update"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[buildAppStore.bat]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "notepadtxt"
info.name = "补充说明"
info.icon = "notepad.png"
info.desc = "补充说明文、SN之类"
info.star = "说明文字"
info.appmode = "runapp"
info.nbapp = "notepadtxt"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[notepad wxsui\ui_appstore\note.txt]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

