-- This source code was auto-generated by updater.bat

AppStore = {}
AppStore.path = '.'

CatalogInfo = {}
AppInfo = {}

local catalog = nil 
local info = {}

CatalogInfo['10-系统维护'] = {}
catalog = CatalogInfo['10-系统维护']
catalog.name = '10-系统维护'
catalog.item = {}

CatalogInfo['11-聊天工具'] = {}
catalog = CatalogInfo['11-聊天工具']
catalog.name = '11-聊天工具'
catalog.item = {}

info = {} 
info.id = "1"
info.name = "腾讯QQ"
info.icon = "QQ.ico"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "网络应用"
info.appmode = "nbapp"
info.nbapp = "qq"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.softmgr.qq.com/original/System/VMware-workstation-full-16.1.2-17966106.exe"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\腾讯软件\\QQ\\腾讯QQ1.lnk"
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.id = "1"
catalog.item[info.id] = info

info = {} 
info.id = "112"
info.name = "微信电脑版"
info.star = "网络应用"
info.desc = "腾讯出品"
info.icon = "WeChat.ico"
info.download_page = "https://dl.qq.com/wechat"
info.direct_url = "https://dl.qq.com/WeChat.exe"
info.appmode = "nbapp"
info.user_agent = qq_user_agent
info.nbapp = "wechat"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "2"
catalog.item[info.id] = info

CatalogInfo['12-影音娱乐'] = {}
catalog = CatalogInfo['12-影音娱乐']
catalog.name = '12-影音娱乐'
catalog.item = {}

info = {} 
info.id = "121"
info.name = "kodi"
info.icon = "kodi.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "kodi"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "3"
catalog.item[info.id] = info

info = {} 
info.id = "122"
info.name = "potplayer"
info.icon = "potplayer.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "potplayer"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "4"
catalog.item[info.id] = info

info = {} 
info.id = "123"
info.name = "vlc播放器"
info.icon = "vlc播放器.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "vlc"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "5"
catalog.item[info.id] = info

CatalogInfo['13-文档办公'] = {}
catalog = CatalogInfo['13-文档办公']
catalog.name = '13-文档办公'
catalog.item = {}

info = {} 
info.id = "131"
info.name = "wps2016"
info.icon = "wps.png"
info.desc = "金山出品"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "wps2016"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "6"
catalog.item[info.id] = info

CatalogInfo['14-远程工具'] = {}
catalog = CatalogInfo['14-远程工具']
catalog.name = '14-远程工具'
catalog.item = {}

info = {} 
info.id = "141"
info.name = "Alpemix远程"
info.icon = "Alpemix远程.png"
info.desc = "Alpemix远程是国外的免费远程软件"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "Alpemix"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "7"
catalog.item[info.id] = info

info = {} 
info.id = "132"
info.name = "深蓝远程"
info.icon = "Dbadmin.png"
info.desc = "震精网吧界的老牌远程工具，作者一直保证性欲"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "dbadmin"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "8"
catalog.item[info.id] = info

info = {} 
info.id = "133"
info.name = "向日葵"
info.icon = "向日葵.png"
info.desc = "十几年历史的远程软件"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "oray"
info.id = "9"
catalog.item[info.id] = info

info = {} 
info.id = "134"
info.name = "向日葵新版"
info.icon = "向日葵.png"
info.desc = "该版本需要登陆才能使用!"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "oraynew"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "10"
catalog.item[info.id] = info

info = {} 
info.id = "135"
info.name = "ToDesk"
info.icon = "todesk.png"
info.desc = "新品远程软件ToDesk完整版"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "todesk"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "11"
catalog.item[info.id] = info

info = {} 
info.id = "136"
info.name = "ToDeskLite"
info.icon = "todesk.png"
info.desc = "新品远程软件todesk受控端"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "todesklite"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "12"
catalog.item[info.id] = info

CatalogInfo['15-虚拟机类'] = {}
catalog = CatalogInfo['15-虚拟机类']
catalog.name = '15-虚拟机类'
catalog.item = {}

info = {} 
info.id = "152"
info.name = "VM16完整版"
info.icon = "vmware.png"
info.desc = "官方完整版vmware"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vmware"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.softmgr.qq.com/original/System/VMware-workstation-full-16.1.2-17966106.exe"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "vmsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
info.id = "13"
catalog.item[info.id] = info

info = {} 
info.id = "151"
info.name = "Vmware 16"
info.icon = "vmware.png"
info.desc = "史上最伟大网管精简的vmware虚拟机"
info.star = "网络应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.user_agent = qq_user_agent
info.appmode = "nbapp"
info.nbapp = "vm16"
info.runapp = "C:\\windows\\system32\\cmd.exe"
info.id = "14"
catalog.item[info.id] = info

CatalogInfo['yy-其他'] = {}
catalog = CatalogInfo['yy-其他']
catalog.name = 'yy-其他'
catalog.item = {}

