@echo off

echo -- This source code was auto-generated by updater.bat> _main.lua
(
    echo.
	echo AppStore = {}
    echo AppStore.path = '.'
	echo AppStore.config = {}
    ::echo AppStore.config['close_runapp_clicked'] = 0
   :: echo AppStore.config['hide_runapp_clicked'] = 1
    echo.
    echo CatalogInfo = {}
    echo AppInfo = {}
    echo.
    echo local catalog = nil 
    echo local info = {}
    echo.
)>>  _main.lua

for /f "delims=" %%i in ('dir /b /ad') do call :catalog_info %%i
::::exit

::pause
goto :EOF

:catalog_info

(
    echo CatalogInfo['%1'] = {}
    echo catalog = CatalogInfo['%1']
    echo catalog.name = '%1'
    echo catalog.item = {}
    echo catalog.size = 0
    echo.
)>>  _main.lua

for /f "delims=" %%i in ('dir /b %1\*.lua') do call :app_info "%1\%%i"
goto :EOF

:app_info
if "x%~n1"=="x找不到文件" goto :EOF
echo     %1 ---  %~n1

rem reset info table
echo info = {} >>  _main.lua
type "%1" >>  _main.lua
(
    echo.
    echo AppInfo[info.id] = info
    echo catalog.size = catalog.size + 1
    echo catalog.item[catalog.size] = info
    echo.
)>>  _main.lua

goto :EOF
