-- This source code was auto-generated by updater.bat

AppMenu = {}
AppMenu.path = '.'

CatalogInfo = {}
AppInfo = {}

local catalog = nil 
local info = {}

CatalogInfo['11平台'] = {}
catalog = CatalogInfo['11平台']
catalog.name = '11平台'
catalog.item = {}

info = {} 

info.id = '11平台.lnk'
info.name = '11平台'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\11平台\11平台.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = '卸载11平台.lnk'
info.name = '卸载11平台'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\11平台\卸载11平台.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['7-Zip'] = {}
catalog = CatalogInfo['7-Zip']
catalog.name = '7-Zip'
catalog.item = {}

info = {} 

info.id = '7-Zip File Manager.lnk'
info.name = '7-Zip File Manager'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\7-Zip\7-Zip File Manager.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = '7-Zip Help.lnk'
info.name = '7-Zip Help'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\7-Zip\7-Zip Help.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['Accessibility'] = {}
catalog = CatalogInfo['Accessibility']
catalog.name = 'Accessibility'
catalog.item = {}

info = {} 

info.id = 'Speech Recognition.lnk'
info.name = 'Speech Recognition'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessibility\Speech Recognition.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['Accessories'] = {}
catalog = CatalogInfo['Accessories']
catalog.name = 'Accessories'
catalog.item = {}

info = {} 

info.id = 'Math Input Panel.lnk'
info.name = 'Math Input Panel'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Math Input Panel.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Notepad.lnk'
info.name = 'Notepad'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Paint.lnk'
info.name = 'Paint'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Paint.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Quick Assist.lnk'
info.name = 'Quick Assist'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Quick Assist.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Remote Desktop Connection.lnk'
info.name = 'Remote Desktop Connection'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Remote Desktop Connection.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Snipping Tool.lnk'
info.name = 'Snipping Tool'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Steps Recorder.lnk'
info.name = 'Steps Recorder'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Steps Recorder.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Windows Fax and Scan.lnk'
info.name = 'Windows Fax and Scan'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Fax and Scan.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Windows Media Player.lnk'
info.name = 'Windows Media Player'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'Wordpad.lnk'
info.name = 'Wordpad'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Wordpad.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['Administrative'] = {}
catalog = CatalogInfo['Administrative']
catalog.name = 'Administrative'
catalog.item = {}

CatalogInfo['Bandicam'] = {}
catalog = CatalogInfo['Bandicam']
catalog.name = 'Bandicam'
catalog.item = {}

info = {} 

info.id = 'Bandicam.lnk'
info.name = 'Bandicam'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Bandicam\Bandicam.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 

info.id = 'BandiFix.lnk'
info.name = 'BandiFix'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Bandicam\BandiFix.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['Daum'] = {}
catalog = CatalogInfo['Daum']
catalog.name = 'Daum'
catalog.item = {}

CatalogInfo['Defraggler'] = {}
catalog = CatalogInfo['Defraggler']
catalog.name = 'Defraggler'
catalog.item = {}

info = {} 

info.id = 'Defraggler.lnk'
info.name = 'Defraggler'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Defraggler\Defraggler.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

CatalogInfo['e2eSoft'] = {}
catalog = CatalogInfo['e2eSoft']
catalog.name = 'e2eSoft'
catalog.item = {}

CatalogInfo['Enable'] = {}
catalog = CatalogInfo['Enable']
catalog.name = 'Enable'
catalog.item = {}

CatalogInfo['Free'] = {}
catalog = CatalogInfo['Free']
catalog.name = 'Free'
catalog.item = {}

CatalogInfo['Git'] = {}
catalog = CatalogInfo['Git']
catalog.name = 'Git'
catalog.item = {}

info = {} 

info.id = 'Git Bash.lnk'
info.name = 'Git Bash'
info.icon = [[C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git\Git Bash.lnk,F]]
info.star = ''

AppInfo[info.id] = info
catalog.item[info.id] = info

info = {} 
