@echo on

if "x%appdir%"=="x" goto :EOF

set "_main.lua=%~dp0_main.lua"

echo -- This source code was auto-generated by updater.bat> "%_main.lua%"
(
    echo.
    echo AppMenu = {}
    echo AppMenu.path = '.'
    echo.
    echo CatalogInfo = {}
    echo AppInfo = {}
    echo.
    echo local catalog = nil 
    echo local info = {}
    echo.
)>>  "%_main.lua%"

for /f "delims=" %%i in ('dir /b /ad "%appdir%"') do call :catalog_info %%i
pause
goto :EOF

:catalog_info

(
    echo CatalogInfo['%1'] = {}
    echo catalog = CatalogInfo['%1']
    echo catalog.name = '%1'
    echo catalog.item = {}
    echo.
)>>  "%_main.lua%"

for /f "delims=" %%i in ('dir /b "%appdir%\%1\*.lnk"') do call :app_info "%~1\%%i"
goto :EOF

:app_info
if "x%~n1"=="x找不到文件" goto :EOF
echo     %1 ---  %~n1

rem reset info table
echo info = {} >>  "%_main.lua%"
(
    echo.
    echo info.id = '%~nx1'
    echo info.name = '%~n1'
    echo info.icon = [[%appdir%\%~1,F]]
    echo info.star = ''
    echo.
    echo AppInfo[info.id] = info
    echo catalog.item[info.id] = info
    echo.
)>>  "%_main.lua%"

goto :EOF
